### ISSUE TITLE
Plugin doesn't appear in plugins list in QGIS 2.18

### ISSUE THREAD

**Issue by Tybion** [gilliM/PLCS#6]
Hello, Gillian.
This looks to be exactly what I need for adjusting a total magnetic intensity 1vd image, but it does not appear in the plugins list in QGIS.
Can I use it in QGIS 2.18?

**Comment by gilliM** [comment]
I cannot ensure that it will, but you can try. You need to activate the experimental plugins in the settings.

**Comment by Tybion** [comment]
Thanks, Gillian.  That worked.  'raster PLCS' then appeared in the list.

For your information, when I open a raster image, the following is reported by QGIS ..
```
2018-05-20T13:33:34	1	Traceback (most recent call last):
			  File "/home/david/.qgis2/python/plugins/PLCS/widgets/mainDock.py", line 75, in layerChanged
			    passed = self.getData(layer)
			  File "/home/david/.qgis2/python/plugins/PLCS/widgets/mainDock.py", line 132, in getData
			    self.imageList.append(self.arrayToImage(data[0::10, 0::10]))
			  File "/home/david/.qgis2/python/plugins/PLCS/widgets/mainDock.py", line 333, in arrayToImage
			    (a.astype('b')).tostring())
			  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 2063, in fromstring
			    "Please call frombytes() instead.")
			Exception: fromstring() has been removed. Please call frombytes() instead.
```
